import {
  Box,
  Button,
  Center,
  Heading,
  Text,
  Checkbox,
  CheckboxGroup,
} from "@chakra-ui/react";
import { motion } from "framer-motion";
import { NextPage } from "next";
import Link from "next/link";

const itemVariant = { hidden: { opacity: 0 }, show: { opacity: 1 } };

const Categories: NextPage = () => {
  return (
    <Center minH="100vh">
      <Box
        w="lg"
        variants={{
          hidden: { opacity: 0 },
          show: { opacity: 1, transition: { staggerChildren: 0.2 } },
        }}
        initial="hidden"
        animate="show"
        as={motion.div}
      >
        <Heading
          size="xl"
          variants={itemVariant}
          as={motion.h1}
          layoutId="heading"
        >
          Choose your interests.
        </Heading>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          World News
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Politics
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Business
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Finance
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Sports
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Entertainment
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Technology
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Health
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Science
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Education
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Environment
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Crime
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Immigration
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Religion
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Lifestyle
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Fashion
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Travel
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Food
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Art
        </Checkbox>
        <Checkbox
          mt={2}
          size="lg"
          color="dimgray"
          display="block"
          variants={itemVariant}
          as={motion.text}
        >
          Weather
        </Checkbox>
      </Box>
    </Center>
  );
};

export default Categories;
